apiVersion: v1
kind: Secret
metadata:
  name: django-secret
type: Opaque
stringData:
  SECRET_KEY: wt(0-q$rj3r5$3q^8k(kv6r^_92$@daka_)+6xlga*j0w85!u^
  DB_NAME: extraction_db
  DB_USER: extraction_user
  DB_PASSWORD: strongpassword123
  DEBUG: "False"
  ALLOWED_HOSTS: demo.local
